baseurl = "https://mtgrunt.github.io"
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "Miles Wallace" 
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Hello. 👋" # Set a different text for the header on the home page
  < img src="img/cartoon.png" alt="My cartoon image" >
  subtitle = "I’m Miles and I'm a computer support analyst by day and a web developer by night. I am interested in new trends and technologies related to CSS3, HTML5, JavaScript and Python techniques. As part of my workflow, I love open-source."
  date_format = "Mon, 2. Jan. 2006"
  mainSections = ["post","posts"]
  logo = "img/favicon.png" # Expecting square dimensions
  favicon = "/img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

#[Params.staticman]
#  api = "https://<API-ENDPOINT>/v3/entry/{GIT-HOST}/<USERNAME>/<REPOSITORY-BLOGNAME>/master/comments"
#[Params.staticman.recaptcha]
#      sitekey: "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
#      secret: "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  #name = ""
  website = "mileswallace.com"
  email = "mileswallace@lavabit.com"
  #facebook = "username"
  github = "mtgrunt"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "modestwalrus"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1
    body_classes = "open-sans-v15-latin-regular"

[[menu.main]]
    name = "Projects"
    url = "page/projects/"
    weight = 2
    body_classes = "open-sans-v15-latin-regular"

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3
